FROM python:3.10

WORKDIR /

RUN apt-get update && apt-get install --assume-yes curl unzip git && apt-get clean all

RUN wget https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz && tar -zxvf terraform-docs-v0.16.0-linux-amd64.tar.gz && chmod +x terraform-docs && mv terraform-docs /usr/local/bin/ && rm terraform-docs-v0.16.0-linux-amd64.tar.gz

WORKDIR /app
COPY requirements.txt .
RUN pip install --proxy=$http_proxy -r requirements.txt


ENTRYPOINT [ "bash", "scripts/entrypoint.sh" ]

RUN apt-get update
RUN apt-get update && \
    apt-get install -y fonts-liberation xdg-utils \
                       software-properties-common curl unzip wget \
                       xvfb && \
    apt-get clean all


# install geckodriver and firefox
RUN GECKODRIVER_VERSION="v0.31.0" && \
    wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz && \
    tar -zxf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C /usr/local/bin && \
    chmod +x /usr/local/bin/geckodriver

# Install firefox
#RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EF4186FE247510BE
#RUN add-apt-repository -y ppa:ubuntu-mozilla-daily/ppa
RUN apt-get update && apt-get install -y firefox-esr && apt-get clean all

COPY requirements-dev.txt .
RUN pip install --proxy=$http_proxy -r requirements-dev.txt

COPY . .

ENTRYPOINT ["bash"]
