"""Add provider category table

Revision ID: 017d76f98581
Revises: efa8ceceaeae
Create Date: 2023-10-17 07:59:04.299977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017d76f98581'
down_revision = 'efa8ceceaeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('slug', sa.String(length=128), nullable=True),
    sa.Column('user_selectable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.add_column('provider', sa.Column('provider_category_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_provider_provider_category_id_provider_category_id', 'provider', type_='foreignkey')
    with op.batch_alter_table('provider') as batch_op:
        batch_op.drop_column('provider_category_id')
    op.drop_table('provider_category')
    # ### end Alembic commands ###
