"""Update analaytics to perform no action when parent module version is deleted

Revision ID: 0776813feaeb
Revises: ef71db86c2a1
Create Date: 2022-06-25 09:55:37.820127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0776813feaeb'
down_revision = 'ef71db86c2a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.create_foreign_key(None, 'analytics', 'module_version', ['parent_module_version'], ['id'], onupdate='CASCADE', ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.create_foreign_key(None, 'analytics', 'module_version', ['parent_module_version'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
