"""Remove erroneous module analytics

Revision ID: 11cd3deaed38
Revises: 161e0f33603c
Create Date: 2022-12-11 19:13:05.410225

"""
import os
import re

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cd3deaed38'
down_revision = '161e0f33603c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if os.environ.get('DB_UPGRADE_REMOVE_ERRONEOUS_ANALYTICS', False):
        uuid_match = re.compile(r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', re.I)
        c = op.get_bind()
        res = c.execute(
            sa.sql.text("""
                SELECT analytics_token from analytics GROUP BY analytics_token
            """
            )
        )
        for row in res:
            # If analytics token matches UUID4 pattern,
            # remove any analytics for this token
            if uuid_match.match(row['analytics_token']):
                c.execute(
                    sa.sql.text(
                        """DELETE FROM analytics WHERE analytics_token=:analytics_token""",
                    ),
                    analytics_token=row['analytics_token']
                )

    # ### end Alembic commands ###


def downgrade():
    pass
