"""Add column to module version to indicate whether extraction has been completed

Revision ID: 1466f38e8059
Revises: a93f5806c0e5
Create Date: 2023-03-11 09:36:13.067413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1466f38e8059'
down_revision = 'a93f5806c0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_version') as batch_op:
        batch_op.add_column(sa.Column('extraction_complete', sa.BOOLEAN(), nullable=True))

    # Update flag on all rows
    bind = op.get_bind()
    bind.execute("""UPDATE module_version SET extraction_complete=1""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_version') as batch_op:
        batch_op.drop_column('extraction_complete')

    # ### end Alembic commands ###
