"""Add namespace display_name

Revision ID: 210586684f86
Revises: 71d311c23025
Create Date: 2023-01-24 07:07:45.170022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210586684f86'
down_revision = '71d311c23025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespace', sa.Column('display_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namespace', 'display_name')
    # ### end Alembic commands ###
