"""Add table for storing provider version binaries

Revision ID: 258fe6ad5ebc
Revises: b10d994c086c
Create Date: 2023-10-23 06:29:25.138826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258fe6ad5ebc'
down_revision = 'b10d994c086c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_version_binary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('operating_system', sa.Enum('FREEBSD', 'DARWIN', 'WINDOWS', 'LINUX', name='providerbinaryoperatingsystemtype'), nullable=False),
    sa.Column('architecture', sa.Enum('AMD64', 'ARM', 'ARM64', 'I386', name='providerbinaryarchitecturetype'), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['provider_version_id'], ['provider_version.id'], name='fk_provider_version_documentation_provider_version_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_version_binary')
    # ### end Alembic commands ###
