"""Add git ref column to module version table

Revision ID: 2bc9677e93d1
Revises: ee14b27baeb1
Create Date: 2024-02-26 05:33:08.413995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc9677e93d1'
down_revision = 'ee14b27baeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_version', sa.Column('git_sha', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_version', 'git_sha')
    # ### end Alembic commands ###
