"""Add submodule type field

Revision ID: 457bcd3d5516
Revises: b6610a495617
Create Date: 2022-04-29 07:14:13.736543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457bcd3d5516'
down_revision = 'b6610a495617'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submodule', sa.Column('type', sa.String(), nullable=True))

    # Set all existing submodules to submodule type
    op.execute("UPDATE submodule SET type = 'submodule'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submodule', 'type')
    # ### end Alembic commands ###
