"""empty message

Revision ID: 496417adb30f
Revises: aef5947a7e1d
Create Date: 2022-05-06 18:26:56.143318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496417adb30f'
down_revision = 'aef5947a7e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
