"""Add git_path to module provider table

Revision ID: 51d3707d6334
Revises: 437ccafb9882
Create Date: 2022-07-22 07:57:02.500034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d3707d6334'
down_revision = '437ccafb9882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_provider', sa.Column('git_path', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_provider', 'git_path')
    # ### end Alembic commands ###
