"""Add logo URL to repository model

Revision ID: 609c0df61fd6
Revises: da1f8ee55821
Create Date: 2023-10-27 05:13:42.315586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609c0df61fd6'
down_revision = 'da1f8ee55821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository") as batch_op:
        batch_op.drop_column('logo_url')
    # ### end Alembic commands ###
