"""Add module version column for extraction version

Revision ID: 71d311c23025
Revises: 8b594ed19f9d
Create Date: 2023-01-22 09:18:23.880577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d311c23025'
down_revision = '8b594ed19f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_version', sa.Column('extraction_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_version', 'extraction_version')
    # ### end Alembic commands ###
