"""Add type to namespace table

Revision ID: 904ba21a396a
Revises: d66dee853b24
Create Date: 2023-10-13 07:38:28.276696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904ba21a396a'
down_revision = 'd66dee853b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('namespace', sa.Column('type', sa.Enum('NONE', 'GITHUB_USER', 'GITHUB_ORGANISATION', name='namespacetype'), nullable=True))
    op.execute("""UPDATE namespace set `type`='NONE'""")
    with op.batch_alter_table("namespace") as batch_op:
        batch_op.alter_column("type", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('namespace', 'type')
    # ### end Alembic commands ###
