"""Add internal flag column to module_provider table

Revision ID: 90650a4010f3
Revises: b0f952e4a027
Create Date: 2022-05-26 18:18:50.070959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90650a4010f3'
down_revision = 'b0f952e4a027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_provider', sa.Column('internal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_provider', 'internal')
    # ### end Alembic commands ###
