"""Add git_path_template column to git provider

Revision ID: 9dbcb4240c55
Revises: 2bc9677e93d1
Create Date: 2024-03-25 07:11:36.123751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbcb4240c55'
down_revision = '2bc9677e93d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('git_provider', sa.Column('git_path_template', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('git_provider') as batch_op:
        batch_op.drop_column('git_path_template')
    # ### end Alembic commands ###
