"""Add table for module version extraction status

Revision ID: a93f5806c0e5
Revises: 210586684f86
Create Date: 2023-03-11 08:30:55.449562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a93f5806c0e5'
down_revision = '210586684f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_extraction_status',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('module_version_id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('last_update', sa.DateTime(), nullable=True),
        sa.Column('status', sa.Enum('IN_PROGRESS', 'FAILED', 'COMPLETE', name='moduleextractionstatustype'), nullable=True),
        sa.Column('message', sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(['module_version_id'], ['module_version.id'], name='fk_module_extraction_status_module_version_id_module_version_id', onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_extraction_status')
    # ### end Alembic commands ###
