"""Add table for provider analytics

Revision ID: ab6edde0b2ef
Revises: baf02ad968b6
Create Date: 2023-10-24 07:22:29.877556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6edde0b2ef'
down_revision = 'baf02ad968b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_version_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('terraform_version', sa.String(length=128), nullable=True),
    sa.Column('namespace_name', sa.String(length=128), nullable=True),
    sa.Column('provider_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_analytics')
    # ### end Alembic commands ###
