"""Add git_tag field to provider version

Revision ID: b10d994c086c
Revises: d1eab00b4da1
Create Date: 2023-10-22 15:27:51.619731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10d994c086c'
down_revision = 'd1eab00b4da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_version', sa.Column('git_tag', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_version") as batch_op:
        batch_op.drop_column('git_tag')
    # ### end Alembic commands ###
