"""Add protocol_versions column to provider version table

Revision ID: baf02ad968b6
Revises: 258fe6ad5ebc
Create Date: 2023-10-23 08:11:28.698230

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'baf02ad968b6'
down_revision = '258fe6ad5ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_version', sa.Column('protocol_versions', sa.LargeBinary(length=16777215).with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_version") as batch_op:
        batch_op.drop_column('protocol_versions')
    # ### end Alembic commands ###
