"""Add provider version document table

Revision ID: d1eab00b4da1
Revises: d6a14e41b2d0
Create Date: 2023-10-21 07:24:07.278783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1eab00b4da1'
down_revision = 'd6a14e41b2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_version_documentation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_version_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('documentation_type', sa.Enum('OVERVIEW', 'PROVIDER', 'RESOURCE', 'DATA_SOURCE', 'GUIDE', name='providerdocumentationtype'), nullable=False),
    sa.Column('content', sa.LargeBinary(length=16777215).with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['provider_version_id'], ['provider_version.id'], name='fk_provider_version_documentation_provider_version_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_version_documentation')
    # ### end Alembic commands ###
