"""Add description and clone_url to repository

Revision ID: d6a14e41b2d0
Revises: f2601a444a07
Create Date: 2023-10-20 18:05:38.445455

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6a14e41b2d0'
down_revision = 'f2601a444a07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository") as batch_op:
        batch_op.add_column(sa.Column('description', sa.LargeBinary(length=16777215).with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('clone_url', sa.String(length=1024), nullable=True))
    with op.batch_alter_table("provider") as batch_op:
        batch_op.drop_column("description")
        batch_op.add_column(sa.Column('description', sa.LargeBinary(length=16777215).with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository") as batch_op:
        batch_op.drop_column('clone_url')
        batch_op.drop_column('description')
    # ### end Alembic commands ###
