"""Add description and title fields for provider documentation

Revision ID: da1f8ee55821
Revises: ab6edde0b2ef
Create Date: 2023-10-26 06:36:49.769055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da1f8ee55821'
down_revision = 'ab6edde0b2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_version_documentation', sa.Column('title', sa.String(length=128), nullable=True))
    op.add_column('provider_version_documentation', sa.Column('description', sa.LargeBinary(length=16777215).with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("provider_version_documentation") as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('title')
    # ### end Alembic commands ###
