"""Add internal flag column to module_version table and foreign key to module provider to point to latest version

Revision ID: ef71db86c2a1
Revises: b0f952e4a027
Create Date: 2022-06-01 06:50:03.299444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef71db86c2a1'
down_revision = 'b0f952e4a027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_provider', sa.Column('latest_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'module_provider', 'module_version', ['latest_version_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL', use_alter=True)
    op.add_column('module_version', sa.Column('internal', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_version', 'internal')
    op.drop_constraint(None, 'module_provider', type_='foreignkey')
    op.drop_column('module_provider', 'latest_version_id')
    # ### end Alembic commands ###
