"""Add provider source auth to session

Revision ID: efa8ceceaeae
Revises: 232f97efb691
Create Date: 2023-10-16 07:48:50.273933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efa8ceceaeae'
down_revision = '232f97efb691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('provider_source_auth', sa.LargeBinary(length=16777215).with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session') as batch_op:
        batch_op.drop_column('provider_source_auth')
    # ### end Alembic commands ###
