"""Add authentication key to repository

Revision ID: f2601a444a07
Revises: ff09d91b2ac4
Create Date: 2023-10-20 06:04:17.329260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2601a444a07'
down_revision = 'ff09d91b2ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository', sa.Column('authentication_key', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("repository") as batch_op:
        batch_op.drop_column('authentication_key')

    # ### end Alembic commands ###
