"""Remove module_version.artifact_location column

Revision ID: f3fe64700304
Revises: 457bcd3d5516
Create Date: 2022-05-06 06:38:09.147500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fe64700304'
down_revision = '457bcd3d5516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_version', 'artifact_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_version', sa.Column('artifact_location', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
