"""Add archive_git_path column to module provider

Revision ID: f9a80ea383cc
Revises: 2bc9677e93d1
Create Date: 2024-03-14 06:05:26.867657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a80ea383cc'
down_revision = '2bc9677e93d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_provider', sa.Column('archive_git_path', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('module_provider', 'archive_git_path')
    # ### end Alembic commands ###
