"""Add archive_git_path column to module provider

Revision ID: f9a80ea383cc
Revises: 9dbcb4240c55
Create Date: 2024-03-14 06:05:26.867657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a80ea383cc'
down_revision = '9dbcb4240c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_git_path', sa.Boolean(), nullable=True))
    with op.batch_alter_table('module_version', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_git_path', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('git_path', sa.String(length=1024), nullable=True))

    bind = op.get_bind()
    module_provider_paths = bind.execute("""SELECT id, git_path FROM module_provider""")
    for module_provider_id, git_path in module_provider_paths:
        bind.execute(
            sa.sql.text(
                """
                UPDATE module_version
                SET git_path=:git_path
                WHERE module_provider_id=:module_provider_id"""
            ),
            git_path=git_path,
            module_provider_id=module_provider_id,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_provider', schema=None) as batch_op:
        batch_op.drop_column('archive_git_path')
    with op.batch_alter_table('module_version', schema=None) as batch_op:
        batch_op.drop_column('archive_git_path')
        batch_op.drop_column('git_path')
    # ### end Alembic commands ###
