"""Add provider version and latest version ID

Revision ID: ff09d91b2ac4
Revises: 017d76f98581
Create Date: 2023-10-19 06:15:45.525433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff09d91b2ac4'
down_revision = '017d76f98581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('gpg_key_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('beta', sa.BOOLEAN(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gpg_key_id'], ['gpg_key.id'], name='fk_provider_version_gpg_key_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name='fk_provider_version_provider_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider') as batch_op:
        batch_op.add_column(sa.Column('latest_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_provider_latest_version_id_provider_version_id', 'provider_version', ['latest_version_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider') as batch_op:
        batch_op.drop_constraint('fk_provider_latest_version_id_provider_version_id', type_='foreignkey')
        batch_op.drop_column('latest_version_id')
    op.drop_table('provider_version')
    # ### end Alembic commands ###
